spring.application.name=wechat

spring.datasource.url=jdbc:postgresql://ep-weathered-recipe-ao8uibag-pooler.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_aFroCS1u6twE
spring.datasource.driver-class-name=org.postgresql.Driver