logging.level.main.com.chat.wechat=INFO
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never
