package main.com.chat.wechat.audit.model;

public enum AuditLogAction {
	AUTH_LOGIN_SUCCESS,
	AUTH_LOGIN_FAILED,
	AUTH_LOGOUT,
	AUTH_REFRESH_TOKEN,
	AUTH_PASSWORD_CHANGE,
	AUTH_EMAIL_VERIFY,

	USER_CREATE,
	USER_UPDATE,
	USER_STATUS_CHANGE,
	USER_ROLE_CHANGE,
	USER_DELETE,

	CONVERSATION_CREATE,
	CONVERSATION_UPDATE,
	CONVERSATION_DELETE,
	CONVERSATION_MEMBER_ADD,
	CONVERSATION_MEMBER_REMOVE,
	CONVERSATION_MEMBER_ROLE_CHANGE,

	MESSAGE_CREATE,
	MESSAGE_EDIT,
	MESSAGE_RECALL,
	MESSAGE_DELETE_FOR_ME,
	MESSAGE_REACTION_ADD,
	MESSAGE_REACTION_REMOVE,

	ATTACHMENT_UPLOAD,
	ATTACHMENT_DOWNLOAD,
	ATTACHMENT_DELETE,

	NOTIFICATION_PREFERENCE_UPDATE,

	MODERATION_REPORT_CREATE,
	MODERATION_REPORT_REVIEW,
	MODERATION_MESSAGE_HIDE,
	MODERATION_MESSAGE_DELETE,
	MODERATION_USER_WARN,
	MODERATION_USER_BAN,

	SYSTEM_CONFIG_UPDATE,
	SECURITY_ACCESS_DENIED
}
